import {build} from 'esbuild';
import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));process.chdir(root);
const config=JSON.parse(await readFile('public-config.json','utf8'));
if(Object.keys(config).some(key=>/secret|plantnet|api.?key/i.test(key)))throw new Error('Secret keys cannot be included in public config.');
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});
const result=await build({entryPoints:['src/main.jsx'],bundle:true,minify:true,write:false,outfile:'dist/app.js',format:'iife',target:['es2020'],define:{'process.env.NODE_ENV':'"production"'},legalComments:'external',metafile:true});
execFileSync(process.execPath,['node_modules/tailwindcss/lib/cli.js','-i','src/styles.css','-o','dist/styles.css','--minify'],{stdio:'inherit'});
let fontCss=await readFile('node_modules/@fontsource/noto-sans-kr/400.css','utf8');
fontCss=fontCss.replace(/, url\([^)]*\.woff\) format\('woff'\)/g,'');
const fontUrls=[...new Set([...fontCss.matchAll(/url\((\.\/files\/[^)]+\.woff2)\)/g)].map(m=>m[1]))];
const fontData=await Promise.all(fontUrls.map(async path=>[path,(await readFile('node_modules/@fontsource/noto-sans-kr/'+path)).toString('base64')]));
for(const [url,encoded]of fontData)fontCss=fontCss.split('url('+url+')').join('url(data:font/woff2;base64,'+encoded+')');
const css=fontCss+'\n'+await readFile('dist/styles.css','utf8');
const js=result.outputFiles.find(file=>!file.path.endsWith('.LEGAL.txt')).text.replace(/<\/script/gi,'<\\/script');
const publicScript='window.plantConfig='+JSON.stringify(config).replace(/</g,'\\u003c')+';';
const template=await readFile('index.template.html','utf8');
const html=template.replace('__APP_CSS__',()=>css).replace('__PUBLIC_CONFIG__',()=>publicScript).replace('__APP_JS__',()=>js);
await writeFile('dist/index.html',html);await writeFile('code_artifact.html',html);
await cp('public','dist',{recursive:true,filter:source=>!source.endsWith('/README.txt')});
for(const file of result.outputFiles.filter(file=>file.path.endsWith('.LEGAL.txt')))await writeFile('dist/LICENSES.txt',file.text);
await writeFile('dist/FONT-LICENSE.txt',await readFile('node_modules/@fontsource/noto-sans-kr/LICENSE'));
await rm('dist/styles.css');
const hash=value=>"'sha256-"+createHash('sha256').update(value).digest('base64')+"'";
const csp=["default-src 'self'","script-src 'self' "+hash(publicScript)+' '+hash(js)+" https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/recaptcha/","style-src 'self' 'unsafe-inline'","font-src 'self' data:","img-src 'self' data: blob: https://www.gstatic.com https://www.google.com","connect-src 'self' https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://*.cloudfunctions.net https://*.run.app https://*.firebaseapp.com https://www.google.com https://www.recaptcha.net","frame-src https://*.firebaseapp.com https://maps.google.com https://www.google.com https://www.recaptcha.net","object-src 'none'","base-uri 'self'","frame-ancestors 'none'"].join('; ');
const firebase=JSON.parse(await readFile('firebase.base.json','utf8'));
firebase.hosting={public:'dist',ignore:['firebase.json','**/.*','**/node_modules/**'],headers:[{source:'**',headers:[{key:'Content-Security-Policy',value:csp},{key:'X-Content-Type-Options',value:'nosniff'},{key:'Referrer-Policy',value:'no-referrer'},{key:'X-Frame-Options',value:'DENY'},{key:'Permissions-Policy',value:'camera=(self), geolocation=(self), microphone=()'},{key:'Cache-Control',value:'no-store'}]}]};
await writeFile('firebase.json',JSON.stringify(firebase,null,2)+'\n');
await writeFile('build-meta.json',JSON.stringify({inputCount:Object.keys(result.metafile.inputs).length,htmlBytes:Buffer.byteLength(html),secretKeysBundled:false},null,2)+'\n');
console.log('Production HTML built:',Buffer.byteLength(html),'bytes; no runtime Babel/Tailwind CDN.');
